services:
  - type: web
    name: taaft-nextjs-native
    runtime: static
    plan: free
    rootDir: .
    buildCommand: "true"
    staticPublishPath: sites/nextjs/out
    autoDeployTrigger: off

  - type: web
    name: taaft-hugo-native
    runtime: static
    plan: free
    rootDir: .
    buildCommand: "true"
    staticPublishPath: sites/hugo/public
    autoDeployTrigger: off

  - type: web
    name: taaft-mkdocs-native
    runtime: static
    plan: free
    rootDir: .
    buildCommand: "true"
    staticPublishPath: sites/mkdocs/site
    autoDeployTrigger: off
