import Link from "next/link";
import { getCategories, getTools } from "../lib/tools";

function ToolCard({ tool }) {
  return (
    <article className="tool-card">
      <div className="tool-top">
        <span className="tool-category">{tool.category}</span>
        <span className="tool-pricing">{tool.pricing}</span>
      </div>
      <h3>{tool.name}</h3>
      <p>{tool.description}</p>
      <div className="tool-footer">
        <span>{tool.domain || "Unknown domain"}</span>
        <Link className="tool-link" href={`/tools/${tool.toolSlug}`}>
          View details
        </Link>
      </div>
    </article>
  );
}

export default function HomePage() {
  const tools = getTools();
  const categories = getCategories();

  return (
    <div className="page-shell">
      <header className="site-header">
        <div className="brand-block">
          <div className="brand-mark">N</div>
          <div>
            <div><strong>AI Tools Directory</strong></div>
            <div className="meta-note">Static directory with category pages and tool detail pages</div>
          </div>
        </div>
        <a href="#directory">Browse tools</a>
      </header>

      <main>
        <section className="hero">
          <div>
            <div className="badge">Native framework build</div>
            <h1>
              Next.js for a static <span>AI tools directory</span>
            </h1>
            <p>
              This version is built natively by Next.js and exported as a static site. It includes
              category pages, dedicated tool pages, and 500 AI tools ready to browse.
            </p>
            <div className="hero-meta">
              <div className="meta-card">
                <div className="meta-label">Tool count</div>
                <div className="meta-value">{tools.length}</div>
              </div>
              <div className="meta-card">
                <div className="meta-label">Categories</div>
                <div className="meta-value">{categories.length}</div>
              </div>
              <div className="meta-card accent-card">
                <div className="meta-label">Output</div>
                <div className="meta-value">Static export</div>
              </div>
            </div>
            <div className="button-row">
              <a className="button button-primary" href="#directory">
                Explore tools
              </a>
            </div>
          </div>
          <aside className="hero-panel">
            <h2>Category pages</h2>
            <p>Every category gets a dedicated static route. Every tool gets its own static route.</p>
            <div className="category-pills">
              {categories.map((category) => (
                <Link key={category.slug} className="pill" href={`/categories/${category.slug}`}>
                  {category.name}
                </Link>
              ))}
            </div>
          </aside>
        </section>

        <section className="directory" id="directory">
          <div className="section-head">
            <div>
              <h2>All 500 tools</h2>
              <p className="meta-note">Static HTML output generated by the framework build.</p>
            </div>
          </div>
          <div className="tool-grid">
            {tools.map((tool) => (
              <ToolCard key={tool.toolSlug} tool={tool} />
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
